# Generated by Django 4.0.4 on 2022-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DETAIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('detail', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
