# Generated by Django 4.0.4 on 2022-06-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_detail_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
