# Generated by Django 4.0.4 on 2022-06-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_detail_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='product_name',
        ),
    ]
