# Generated by Django 4.0.4 on 2022-06-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_detail_price_detail_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='final',
            field=models.IntegerField(default=0),
        ),
    ]
