# Generated by Django 4.0.4 on 2022-06-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_detail_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('product_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
