# Generated by Django 4.0.4 on 2022-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cart_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
