# Generated by Django 4.0.4 on 2022-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cart_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unique',
            field=models.IntegerField(default=0),
        ),
    ]
