# Generated by Django 4.0.4 on 2022-07-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.CharField(default='', max_length=100)),
                ('twit', models.CharField(default='', max_length=100)),
                ('face', models.CharField(default='', max_length=100)),
                ('favourite', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
